# This is a basic workflow to help you get started with Actions
name: PRECOMMIT

# setup like the pie repo for this test
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
      - "**"
    paths:
      - "**"

  push:
    branches:
      - main
    paths:
      - "**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  format:
    name: format
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - black
          - isort
    steps:
    - uses: actions/checkout@v3
      with:
        # required to grab the history of the PR
        fetch-depth: 0
    - name: Determine Git Refs for a Push
      if: github.event_name == 'push'
      run: |
        echo "BASE=${{ github.event.before }}" >> $GITHUB_ENV
        echo "HEAD=${{ github.event.after }}" >> $GITHUB_ENV
    - name: Determine Git Refs for a PR
      if: github.event_name == 'pull_request'
      run: |
        echo "BASE=${{ github.event.pull_request.base.sha }}" >> $GITHUB_ENV
        echo "HEAD=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
    - uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: ${{ matrix.command }} --from-ref ${{ env.BASE }} --to-ref ${{ env.HEAD }}


  test:
    name: testvars
    needs: [format]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Print Env Vars
      run: |
        echo "Base: ${{ env.BASE }} Head: ${{ env.HEAD }}"
