# PIE deploy-kubernetes
# Reusable Workflow
#
# This workflow triggers Kubectl deployments to GKE
# Note:
# deployment triggers should pass only a single K8s Service to be deployed
# multiple services may be deployed by using a GHA matrix to call this workflow

name: reusable-k8s-deploy
on:

  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      dockerfile:
        description: Path to dir containing a Dockerfile
        required: true
        type: string
      service:
        default: api
        description: Target Service to deploy
        required: true
        type: string

  # Allow manually triggered k8s deploy
  workflow_dispatch:
    inputs:
      environment:
        default: phils-apps-stg
        description: Target GCP Project & Stage
        required: true
        type: environment
      service:
        default: api
        description: Target Service to deploy
        options:
          - api
          - api-inference
          - api-operations
          - gains
          - hitting
          - hitting-advance
          - intlblast
          - performance
          - pitching
          - pitchingsandlot
          - poe
          - postgame
          - postgamesandlot
          - promodel
          - rocky
          - ws
        required: true
        type: choice

env:
  #TODO: github env vars???
  phils-apps-stg: microservices-blu
  REGION: us-east1
  NAMESPACE: apps

jobs:
  # deploy:
  #   environment: inputs.environment
  #   name: ⬡ Deploy to GKE (Kubernetes)
  #   outputs:
  #     cluster_id: ${{ env[inputs.environment] }}
  #     image_ref: ${{ env.DEPLOYED_IMAGE }}@${{ env.LATEST_SHA }}
  #   runs-on: ubuntu-24.04
  #   steps:

  #     - name: Checkout code
  #       uses: actions/checkout@v4

  print:
    environment: inputs.environment
    runs-on: ubuntu-24.04
    steps:
      # properties of the JSON object are now available
     - run: echo ${{ inputs.name }}
     - run: echo ${{ inputs.dockerfile }}