# Reusable workflow
name: Terraform fmt

on:
  workflow_call:
    inputs:
      tf-root-dir:
        required: true
        type: string


jobs:
  fmt:
    name: fmt
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check ${{ inputs.tf-root-dir }}
        continue-on-error: false
