# Reusable workflow
name: Terraform plan

on:
  workflow_call:
    inputs:
      tf-root-dir:
        required: true
        type: string
    secrets:
      tf-var:
        required: true

jobs:
  plan:
    name: plan
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform plan
        id: plan
        run: |
          terraform plan \
          -var ${{ inputs.tf-var }}
          -no-color -out=tf.plan ${{ inputs.tf-root-dir }}
        continue-on-error: false
