name: trigger-merge-K8s-deploy
on:
  # allows manual GHA Action run
  workflow_dispatch:

  # automatic GHA run upon any merge into main
  # push:
  #   branches:
  #     - main

jobs:

  all-slices:
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github/config/slices.json
      - name: Set matrix data
        id: set-matrix
        # dump the file into a JSON object keyed 'matrix'
        run: echo "matrix=$(jq -c . < .github/config/slices.json)" >> $GITHUB_OUTPUT

  # DEPLOY TO GKE (Kubernetes)
  deploy-to-gke:
    name: deploy (GKE)
    needs: all-slices
    strategy:
      fail-fast: true
      matrix: ${{ fromJson(needs.all-slices.outputs.matrix) }}
    uses: ./.github/workflows/reusable-k8s-deploy.yaml
    with:
      environment: phils-apps-prd
      service: ${{ matrix.name }}
      dockerfile: ${{ matrix.dockerfile }}
    secrets: inherit
